### ISSUE TITLE
get请求参数

### ISSUE THREAD

**Issue by dalang81** [jadepeng/generator-swagger-2-ts#1]
import API from './api';

declare var require: any;
let service = new API('http://localhost:8090');

let run = async () => await service.fetchAllInPatientsListUsingGET({**admissionSn:'20068598'**});

run().then(data => console.log(data));

----------------
参数没生效啊

**Comment by dalang81** [comment]
{"admissionSn":"20068598"}
{"baseURL":"http://localhost:8090","url":"/patientListInfo/fetchAllInPatientsList","method":"GET"}

**Comment by jadepeng** [comment]
下载新版本，自定义的参数要放到queryParameters里

api.get数据集API().getAllDataSetsAsync({ name: "", $queryParameters: { "test": 1 } }).then(resp => {
    console.log(resp)
})
