### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Su66** [jadepeng/generator-swagger-2-ts#10]
<img width="1484" alt="WechatIMG109" src="https://user-images.githubusercontent.com/28215432/90747367-665d0280-e303-11ea-8718-14eef046bb59.png">
<img width="806" alt="WX20200820-163639@2x" src="https://user-images.githubusercontent.com/28215432/90747388-6c52e380-e303-11ea-8651-230237e7a5b4.png">
Misspelled word~

**Comment by jadepeng** [comment]
3ks, already fixed
