### ISSUE TITLE
泛型支持好像有点问题

### ISSUE THREAD

**Issue by 1098327588** [jadepeng/generator-swagger-2-ts#8]
`泛型返回格式GenericAjaxResult<Page<Location>>` ，用工具生成了下面两个类型。其中
Page«Location» 和PageLocation 对不上
export type GenericAjaxResultPageLocation = {
  code?: number  
  data?: Page«Location»  
  msg?: string  
}
export type PageLocation = {
  current?: number  
  orders?:  Array <OrderItem>
  pages?: number  
  records?:  Array <Location>
  searchCount?: boolean  
  size?: number  
  total?: number  
}

**Comment by jadepeng** [comment]
试下新版本
